spring:
  application:
    name: tanzu-java-web-app
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: always
cloud:
  aws:
    instance:
      data:
        enabled: true