apiVersion: apps/v1
kind: Deployment
metadata:
  name: tanzu-java-web-app
  namespace: tanzu-java-web-app
spec:
  selector:
    matchLabels:
      app: tanzu-java-web-app
  template:
    metadata:
      labels:
        app: tanzu-java-web-app
    spec:
      containers:
      - name: tanzu-java-web-app
        image: tanzu-java-web-app
        ports:
        - containerPort: 8080
