apiVersion: apps/v1
kind: Deployment
metadata:
  name: tanzu-java-web-app
  namespace: tanzu-java-web-app
spec:
  selector:
    matchLabels:
      app: tanzu-java-web-app
  template:
    metadata:
      labels:
        app: tanzu-java-web-app
    spec:
      containers:
      - name: tanzu-java-web-app
        image: tanzu-java-web-app
        ports:
        - name: http
          containerPort: 8080
        startupProbe:
          httpGet:
            path: /livez
            port: http
          failureThreshold: 10
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /livez
            port: http
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
          periodSeconds: 3
